title: "Axegon"
views: "views"
header: "layout/header.html"
contents: "layout/contents.html"
footer: "layout/footer.html"
icon: "static/favicon.ico"
navbarId: "#_navbar"
contentsId: "#_contents"
footerId: "#_footer"
templateDir: "views"
initialPage: "index/index"
debug: false
styles:
  - "static/styles/bulma.min.css"
  - "static/styles/fa.min.css"
  - "static/styles/styles.css"